[build]
  command = "npm run build"
  publish = "out"



[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "max-age=0, no-cache, no-store, must-revalidate"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Cache-Control = "max-age=0, no-cache, no-store, must-revalidate"
